title: "Hongchao Hu"
author: "Jason (Hongchao) Hu"
description: "University of California San Diego 2024 Graduate"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md", title: "About Me"}
  - {file: "HongchaoHuCV.pdf", title: "CV"}
  - {file: "project.md", title: "Project"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "hohu@ucsd.edu"}
  - {title: Github, icon: github, url: "https://github.com/HongchaoHu"}
  - {title: Instagram, icon: address-card, url: "@HHCJASON"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
